name: gndmedia
favicon: null
layout_spectrum: 0
typography_spectrum: 0.5803118655458093
title: gndmedia
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.03922762884758413
  lightness: 0.7391115562058985
  saturation: 0.6807046220637858
  rhythmicContrast: 0.5381463742814958
purpose: []
