name: gndmedia
favicon: null
layout_spectrum: 0.46783
typography_spectrum: 0.25369
title: gndmedia
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#080808'
    - '#838584'
    - '#bcbcbc'
    - '#ffffff'
    - '#494846'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5381463742814958
purpose: []
