name: gndmedia
favicon: null
layout_spectrum: 0.99842
typography_spectrum: 1
title: gndmedia
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#aaaaaa'
    - '#000000'
    - '#ffffff'
    - '#aa5555'
    - '#ff0000'
  brandStrength: 0.5
  lightness: 0.375
  saturation: 0.6875
  rhythmicContrast: 0.5381463742814958
purpose: []
