name: gndmedia
favicon: null
layout_spectrum: 0.50053
typography_spectrum: 0.00158
title: gndmedia
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c2da2f'
    - '#63b5e6'
    - '#1276bc'
    - '#fd261f'
    - '#1e0200'
  brandStrength: 0.03922762884758413
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5381463742814958
purpose: []
